# Generated by Django 6.0.3 on 2026-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
