# Generated by Django 6.0.3 on 2026-03-23 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_category_subcategory_and_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_categories', to=settings.AUTH_USER_MODEL, verbose_name='Takipçiler'),
        ),
    ]
